version: "3"
services:
  server:
    build: .
    ports:
      - 8080:8080
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - COOKIE_SECRET_TOKEN=${COOKIE_SECRET_TOKEN}
      - API_DB_STRING=phobos-api:${MYSQL_PASSWORD}@tcp(172.17.0.1:3308)/phobos
      - FRONTEND_URL=${FRONTEND_URL}
      - SERVER_URL=${SERVER_URL}
      - STRAVA_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GIN_MODE=release
  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: phobos
      MYSQL_USER: phobos-api
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
