version: '3'
services:
  deimos:
    build:
      context: ./deimos
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8080
    ports:
      - 3000:80
  server:
    build: ./server
    ports:
      - 8080:8080
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - API_DB_STRING=${API_DB_STRING}
      - GIN_MODE=release
  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: phobos
      MYSQL_USER: phobos-api
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3308:3306'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
