version: '3'
services:
  server:
    build: ./server
    ports:
      - 8080:8080
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GIN_MODE=release
  deimos:
    build: ./deimos
    ports:
      - 3000:80